//
//  Trails.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class Trails: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _trailId: String?
    var _difficulty: NSNumber?
    var _equipmentInfo: String?
    var _length: String?
    var _location: String?
    var _name: String?
    var _permitInfo: String?
    var _ratings: Set<NSNumber>?
    var _reviews: Set<String>?
    var _season: String?
    var _status: String?
    
    class func dynamoDBTableName() -> String {

        return "weekendwarrior-mobilehub-375828022-Trails"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_trailId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_trailId" : "trailId",
               "_difficulty" : "difficulty",
               "_equipmentInfo" : "equipmentInfo",
               "_length" : "length",
               "_location" : "location",
               "_name" : "name",
               "_permitInfo" : "permitInfo",
               "_ratings" : "ratings",
               "_reviews" : "reviews",
               "_season" : "season",
               "_status" : "status",
        ]
    }
}
